import type { VoucherItem } from './types';
import { getVoucherStatus } from './utils';

export const VOUCHERS_PER_PAGE = 20;

const RAW_INITIAL_VOUCHERS: VoucherItem[] = [
  {
    id: '1',
    code: 'WELCOME20',
    category: ['Food', 'Electronics'],
    scope: 'Percentage',
    type: 'Percentage',
    discount: '20%',
    discountValue: 20,
    minOrder: 'SAR 100',
    maxDiscount: 'SAR 50',
    usage: '145/500',
    usedCount: 145,
    maxUsage: 500,
    expiryDate: '2026-12-31',
    status: 'Active',
    limitOnePerCustomer: true,
  },
  {
    id: '2',
    code: 'FREESHIP',
    category: ['Electronics'],
    scope: 'All',
    type: 'Free Shipping',
    discount: '—',
    discountValue: 0,
    minOrder: 'SAR 200',
    maxDiscount: '—',
    usage: '89/200',
    usedCount: 89,
    maxUsage: 200,
    expiryDate: '2026-09-15',
    status: 'Active',
    limitOnePerCustomer: false,
  },
  {
    id: '3',
    code: 'SAVE50',
    category: ['Fashion', 'Home'],
    scope: 'Category',
    type: 'Amount',
    discount: 'SAR 50',
    discountValue: 50,
    minOrder: 'SAR 300',
    maxDiscount: '—',
    usage: '200/200',
    usedCount: 200,
    maxUsage: 200,
    expiryDate: '2025-01-30',
    status: 'Expired',
    limitOnePerCustomer: true,
  },
  {
    id: '4',
    code: 'VIP10',
    category: ['Beauty'],
    scope: 'Vendor',
    type: 'Percentage',
    discount: '10%',
    discountValue: 10,
    minOrder: 'SAR 50',
    maxDiscount: 'SAR 100',
    usage: '56/100',
    usedCount: 56,
    maxUsage: 100,
    expiryDate: '2026-10-01',
    status: 'Active',
    limitOnePerCustomer: true,
  },
  {
    id: '5',
    code: 'SUMMER30',
    category: ['Food'],
    scope: 'Percentage',
    type: 'Percentage',
    discount: '30%',
    discountValue: 30,
    minOrder: 'SAR 150',
    maxDiscount: 'SAR 75',
    usage: '0/300',
    usedCount: 0,
    maxUsage: 300,
    expiryDate: '2026-08-30',
    status: 'Active',
    limitOnePerCustomer: false,
  },
  {
    id: '6',
    code: 'FLAT100',
    category: ['Home'],
    scope: 'Product',
    type: 'Amount',
    discount: 'SAR 100',
    discountValue: 100,
    minOrder: 'SAR 500',
    maxDiscount: '—',
    usage: '45/100',
    usedCount: 45,
    maxUsage: 100,
    expiryDate: '2024-12-31',
    status: 'Expired',
    limitOnePerCustomer: true,
  },
  {
    id: '7',
    code: 'NEWUSER15',
    category: ['Fashion', 'Beauty'],
    scope: 'All',
    type: 'Percentage',
    discount: '15%',
    discountValue: 15,
    minOrder: 'SAR 80',
    maxDiscount: 'SAR 60',
    usage: '312/1000',
    usedCount: 312,
    maxUsage: 1000,
    expiryDate: '2026-11-20',
    status: 'Active',
    limitOnePerCustomer: true,
  },
  {
    id: '8',
    code: 'ELEC200',
    category: ['Electronics'],
    scope: 'Category',
    type: 'Amount',
    discount: 'SAR 200',
    discountValue: 200,
    minOrder: 'SAR 1000',
    maxDiscount: '—',
    usage: '30/50',
    usedCount: 30,
    maxUsage: 50,
    expiryDate: '2026-08-15',
    status: 'Active',
    limitOnePerCustomer: true,
  },
  {
    id: '9',
    code: 'WEEKEND25',
    category: ['Food', 'Home'],
    scope: 'Percentage',
    type: 'Percentage',
    discount: '25%',
    discountValue: 25,
    minOrder: 'SAR 120',
    maxDiscount: 'SAR 80',
    usage: '178/400',
    usedCount: 178,
    maxUsage: 400,
    expiryDate: '2026-08-05',
    status: 'Active',
    limitOnePerCustomer: false,
  },
  {
    id: '10',
    code: 'BEAUTY5',
    category: ['Beauty'],
    scope: 'Vendor',
    type: 'Percentage',
    discount: '5%',
    discountValue: 5,
    minOrder: 'SAR 30',
    maxDiscount: 'SAR 20',
    usage: '400/400',
    usedCount: 400,
    maxUsage: 400,
    expiryDate: '2025-06-10',
    status: 'Expired',
    limitOnePerCustomer: true,
  },
  {
    id: '11',
    code: 'HOMESALE',
    category: ['Home'],
    scope: 'All',
    type: 'Free Shipping',
    discount: '—',
    discountValue: 0,
    minOrder: 'SAR 250',
    maxDiscount: '—',
    usage: '67/150',
    usedCount: 67,
    maxUsage: 150,
    expiryDate: '2026-09-30',
    status: 'Active',
    limitOnePerCustomer: false,
  },
  {
    id: '12',
    code: 'FASHION40',
    category: ['Fashion'],
    scope: 'Category',
    type: 'Percentage',
    discount: '40%',
    discountValue: 40,
    minOrder: 'SAR 200',
    maxDiscount: 'SAR 120',
    usage: '95/250',
    usedCount: 95,
    maxUsage: 250,
    expiryDate: '2026-10-25',
    status: 'Active',
    limitOnePerCustomer: true,
  },
  {
    id: '13',
    code: 'FLASH60',
    category: ['Electronics', 'Home'],
    scope: 'Product',
    type: 'Amount',
    discount: 'SAR 60',
    discountValue: 60,
    minOrder: 'SAR 400',
    maxDiscount: '—',
    usage: '150/150',
    usedCount: 150,
    maxUsage: 150,
    expiryDate: '2025-03-20',
    status: 'Expired',
    limitOnePerCustomer: true,
  },
  {
    id: '14',
    code: 'RAMADAN20',
    category: ['Food', 'Beauty'],
    scope: 'Percentage',
    type: 'Percentage',
    discount: '20%',
    discountValue: 20,
    minOrder: 'SAR 100',
    maxDiscount: 'SAR 70',
    usage: '210/600',
    usedCount: 210,
    maxUsage: 600,
    expiryDate: '2026-12-01',
    status: 'Active',
    limitOnePerCustomer: false,
  },
  {
    id: '15',
    code: 'STUDENT10',
    category: ['Electronics', 'Fashion'],
    scope: 'All',
    type: 'Percentage',
    discount: '10%',
    discountValue: 10,
    minOrder: 'SAR 50',
    maxDiscount: 'SAR 40',
    usage: '89/300',
    usedCount: 89,
    maxUsage: 300,
    expiryDate: '2026-11-30',
    status: 'Active',
    limitOnePerCustomer: true,
  },
  {
    id: '16',
    code: 'CLEAR75',
    category: ['Home'],
    scope: 'Category',
    type: 'Amount',
    discount: 'SAR 75',
    discountValue: 75,
    minOrder: 'SAR 350',
    maxDiscount: '—',
    usage: '120/120',
    usedCount: 120,
    maxUsage: 120,
    expiryDate: '2025-02-14',
    status: 'Expired',
    limitOnePerCustomer: false,
  },
  {
    id: '17',
    code: 'VENDOR15',
    category: ['Beauty', 'Fashion'],
    scope: 'Vendor',
    type: 'Percentage',
    discount: '15%',
    discountValue: 15,
    minOrder: 'SAR 90',
    maxDiscount: 'SAR 50',
    usage: '44/200',
    usedCount: 44,
    maxUsage: 200,
    expiryDate: '2026-09-10',
    status: 'Active',
    limitOnePerCustomer: true,
  },
  {
    id: '18',
    code: 'FREESHIP2',
    category: ['Food'],
    scope: 'All',
    type: 'Free Shipping',
    discount: '—',
    discountValue: 0,
    minOrder: 'SAR 150',
    maxDiscount: '—',
    usage: '250/500',
    usedCount: 250,
    maxUsage: 500,
    expiryDate: '2026-08-20',
    status: 'Active',
    limitOnePerCustomer: false,
  },
  {
    id: '19',
    code: 'BIGSALE100',
    category: ['Electronics'],
    scope: 'Product',
    type: 'Amount',
    discount: 'SAR 100',
    discountValue: 100,
    minOrder: 'SAR 700',
    maxDiscount: '—',
    usage: '18/60',
    usedCount: 18,
    maxUsage: 60,
    expiryDate: '2026-10-15',
    status: 'Active',
    limitOnePerCustomer: true,
  },
  {
    id: '20',
    code: 'OLDDEAL30',
    category: ['Home', 'Beauty'],
    scope: 'Category',
    type: 'Percentage',
    discount: '30%',
    discountValue: 30,
    minOrder: 'SAR 180',
    maxDiscount: 'SAR 90',
    usage: '300/300',
    usedCount: 300,
    maxUsage: 300,
    expiryDate: '2025-05-05',
    status: 'Expired',
    limitOnePerCustomer: true,
  },
  {
    id: '21',
    code: 'LOYAL20',
    category: ['Fashion', 'Home'],
    scope: 'Vendor',
    type: 'Percentage',
    discount: '20%',
    discountValue: 20,
    minOrder: 'SAR 100',
    maxDiscount: 'SAR 60',
    usage: '134/400',
    usedCount: 134,
    maxUsage: 400,
    expiryDate: '2026-12-10',
    status: 'Active',
    limitOnePerCustomer: false,
  },
  {
    id: '22',
    code: 'GADGET50',
    category: ['Electronics'],
    scope: 'Category',
    type: 'Amount',
    discount: 'SAR 50',
    discountValue: 50,
    minOrder: 'SAR 250',
    maxDiscount: '—',
    usage: '76/200',
    usedCount: 76,
    maxUsage: 200,
    expiryDate: '2026-09-25',
    status: 'Active',
    limitOnePerCustomer: true,
  },
  {
    id: '23',
    code: 'GLOWUP10',
    category: ['Beauty'],
    scope: 'All',
    type: 'Percentage',
    discount: '10%',
    discountValue: 10,
    minOrder: 'SAR 60',
    maxDiscount: 'SAR 30',
    usage: '500/500',
    usedCount: 500,
    maxUsage: 500,
    expiryDate: '2025-04-18',
    status: 'Expired',
    limitOnePerCustomer: false,
  },
  {
    id: '24',
    code: 'TRENDY35',
    category: ['Fashion'],
    scope: 'Percentage',
    type: 'Percentage',
    discount: '35%',
    discountValue: 35,
    minOrder: 'SAR 220',
    maxDiscount: 'SAR 110',
    usage: '60/250',
    usedCount: 60,
    maxUsage: 250,
    expiryDate: '2026-11-05',
    status: 'Active',
    limitOnePerCustomer: true,
  },
  {
    id: '25',
    code: 'KITCHEN80',
    category: ['Home', 'Food'],
    scope: 'Product',
    type: 'Amount',
    discount: 'SAR 80',
    discountValue: 80,
    minOrder: 'SAR 400',
    maxDiscount: '—',
    usage: '95/95',
    usedCount: 95,
    maxUsage: 95,
    expiryDate: '2025-07-01',
    status: 'Expired',
    limitOnePerCustomer: true,
  }
];

export const INITIAL_VOUCHERS: VoucherItem[] = RAW_INITIAL_VOUCHERS.map((v) => ({
  ...v,
  status: getVoucherStatus(v.expiryDate, v.status),
}));

